---
title: 'Examining a Quarter Century of Publishing Trends in Social Work Research:
  A Data Science Perspective'
author: ''
date: "May 26, 2015"
output: html_document
---


`r knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, comment=NA)`



```{r LoadDatabase}
rm(list=ls())
load("HistoricalDatabase.R")

head(full.df)
dim(full.df)
```






```{r colorThemes}
# http://colorbrewer2.org/?type=diverging&scheme=PuOr&n=4

cp <- c("#fdb864", "#e66101", "#b2abd2", "#5e3c99" )
```




```{r summarySetUp, eval=FALSE, cache=TRUE}
unique.titles <- filter(full.df, attributes == "journal") %>%
    group_by(record) %>%
    summarise(N = n())

articles.titleMatching <- length(which(full.df$attributes == "article"))

journals.titleMatching <- filter(full.df, attributes == "journal") %>%
    summarise(Unique = n_distinct(record))

articles.otherDocuments <- length(which(full.df$attributes == "article"))

journals.otherDocuments <- filter(full.df, attributes == "journal") %>% 
    summarise(Unique = n_distinct(record))

articles.final <- length(which(full.df$attributes == "article"))

journals.final <- filter(full.df, attributes == "journal") %>% 
    summarise(Unique = n_distinct(record))

unique.titles <- filter(full.df, attributes == "journal") %>%
    group_by(record) %>%
    mutate(Hodge.list = ifelse(record %in% hodge == TRUE, 1, 0)) %>%
    summarise(N = n(), Hodge.list = max(Hodge.list)) %>%
    mutate(Hodge = ifelse(Hodge.list == 1, "Y", "N"))

n.so.yr <- filter(full.df, attributes == "journal" | attributes == "pubYear")

n.so <- filter(full.df, attributes == "journal") %>% mutate(title = record) %>% 
    select(-attributes, -record)

n.yr <- filter(full.df, attributes == "pubYear") %>% mutate(year = record ) %>% 
    select(-attributes, -record)

unique.titles
```

```{r Figure 1a - Journals, cache=TRUE, eval=FALSE}
cp <- c("#fdb864", "#e66101", "#b2abd2", "#5e3c99" )

#=======================================
# Journals
#=======================================
library(gridExtra)

n.journals.year <- filter(full.df, attributes == "journal") %>%
    select(articleID, record)

n.year <- filter(full.df, attributes == "pubYear") %>%
    select(articleID, record)

n.journals.year <- left_join(n.journals.year, n.year, by = "articleID", copy=TRUE) %>%
    group_by(record.y) %>%
    summarise(Journal.count = n_distinct(record.x)) %>%
    mutate(record.y = as.numeric(record.y))


exp.05 <- c(29, rep(NA, 24)) 
for(i in 2:25){
    exp.05[i] <- exp.05[i-1] + exp.05[i-1]*.05
}

exp.04 <- c(29, rep(NA, 24)) 
for(i in 2:25){
    exp.04[i] <- exp.04[i-1] + exp.04[i-1]*.04
} 

exp.03 <- c(29, rep(NA, 24)) 
for(i in 2:25){
    exp.03[i] <- exp.03[i-1] + exp.03[i-1]*.03
}





n.journals.year$exp.05 <- exp.05
n.journals.year$exp.04 <- exp.04
n.journals.year$exp.03 <- exp.03
n.journals.year <- mutate(n.journals.year, Journal.count = as.numeric(Journal.count))
n.journals.year <- as.data.frame(n.journals.year)

years <- c(1989, 2005, 2013, 2013)
points <- c(29, n.journals.year$Journal.count[c(17,25)], max(n.journals.year$exp.05))
annotate.df <- data.frame(years, points)

cols = c("Observed Growth" = cp[1], "Estimated 3.2% CAGR" = cp[4], "Estimated 5% CAGR" = cp[3])


figure2 <- ggplot(n.journals.year, aes(record.y, 
    y = Journal.count)) + 
    theme_bw() + 
    theme(axis.text.x = element_text(size=8), 
    title = element_text(size = 10), plot.title=element_text(size=10)) + 
    xlab("Year") + 
    ylab("Journals") + 
    scale_y_continuous(breaks = c(seq(0, 100, 10)), limits = c(20, 95)) +
    theme(axis.title.x = element_text(vjust=-0.5), axis.title.y = element_text(vjust=.75)) + 
    geom_line(aes(x = record.y, y = exp.05, colour = "Estimated 5% CAGR"),
        data = n.journals.year,   colour = cp[2], alpha = .80) +
    geom_line(aes(x = record.y, y = exp.04, colour = "Estimated 4% CAGR"), 
        data = n.journals.year,  colour = cp[2], alpha = .80) +
    geom_line(aes(colour = "Observed Growth"), colour = cp[4], size = 1.5) + 
    stat_smooth(method = "lm", se = FALSE, colour = cp[3]) +
    annotate("text", x = 2016.5, y = 60, label = "Observed growth", size = 5) +
    annotate("text", x = 2016.5, y = 70, label = "Linear growth\n (slope=1.9)", size = 5) + 
    annotate("text", x = 2016, y = 76, label = "4% CAGR", size = 5) + 
    annotate("text", x = 2015.5, y = 95, label = "5% CAGR", size = 5) +
    scale_x_continuous(limits = c(1989, 2020), breaks = c(1989, 1993, 1997, 2001, 2005, 2009, 2013)) +
    ggtitle("Figure 2. Observed Versus Estimated Growth of Journals (1989-2013)") + 
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          panel.border = element_blank(), axis.line = element_line(), 
          axis.text.x = element_text(size = 16), 
          axis.text.y = element_text(size = 16), 
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16)) +
    theme(plot.title = element_text(size = 19))




```

```{r Figure 1b - Journals, eval=FALSE}
curr <- n.journals.year$Journal.count[-1]
prev <- n.journals.year$Journal.count[1:(length(n.journals.year$Journal.count)-1)]
annualChange.numeric <- c(0, (100 * (curr-prev)/ prev))
annualChange.dichotomous <- ifelse(annualChange.numeric < 0, "Decrease", "Increase")
annualChange.df <- data.frame(annualChange.numeric, annualChange.dichotomous)
annualChange.df$year <- c(1989:2013)

figure3 <- ggplot(annualChange.df, aes(year, annualChange.numeric, fill =annualChange.dichotomous)) + 
    theme_bw() + 
    geom_bar(stat="identity") +
    scale_fill_manual(values = cp[c(3,1)], limits = c("Increase", "Decrease")) + 
    theme(legend.position = c(1,1), legend.justification = c(1,1), legend.title = element_blank()) + 
    ylab("Percent change") +
    xlab("Year")  +
    scale_x_continuous(breaks=seq(1989, 2015, 4)) + 
    scale_y_continuous(breaks = seq(-10, 15, 5)) + 
    geom_hline(yintercept=seq(-5, 15, 5), col="white", lwd=0.4) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          panel.border = element_blank(), axis.line = element_line(), 
          axis.text.x = element_text(size = 16), 
          axis.text.y = element_text(size = 16), 
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16)) + 
    geom_hline(yintercept=0, col="gray", lwd=0.6, alpha =.8) +
    ggtitle("Figure 3. Annual Percentage Change in the Number Journals (1989 - 2013)") +
    theme(plot.title = element_text(size = 19))

ggsave("figure3.png", figure3, dpi=250)
```



```{r plot02_SmallMultiples, eval=FALSE}
# Remove 2014 & 2015 

# Create an initial data frame from HD
sm.df <- left_join(n.so, n.yr) %>%
    group_by(title, year) %>%
    summarize(N = n()) %>%
    mutate(Overall.N = sum(N), year = as.numeric(year)) %>%
    ungroup() %>%
    arrange(desc(Overall.N), title) %>%
    rename(Year = year, Journal= title) 

# Read Scopus database
scopus.df <- read.csv("/Users/beperron/Git/SocialWorkResearch/Data/scopus.csv")
scopus.df2 <- read.csv("/Users/beperron/Git/SocialWorkResearch/Data/scopus_OldHarvest.csv")


scopus.df$Year <- as.numeric(scopus.df$Year)
scopus.df <- filter(scopus.df, Year <= 2013)

# Join HD with Scopus and join abbreviation names
sm.scopus.merged <-full_join(sm.df, scopus.df, by = c("Journal", "Year")) %>%
    select(Year, Journal, N, Overall.N, Documents)




 sm.scopus.merged.table <- group_by(sm.scopus.merged, Journal) %>%
     summarize(DataBase.N = sum(N, na.rm=TRUE), Scopus.N = sum(Documents, na.rm=TRUE)) %>%
     arrange(desc(DataBase.N))


 abb <- read.csv("/Users/beperron/Git/SocialWorkResearch/Data/master.csv")
 abb$ID <- 1:nrow(abb)
 sm.scopus.merged <- full_join(sm.scopus.merged, abb, by = "Journal") %>% 
     select(-X) %>%
     mutate(Documents = ifelse(Documents == 0, NA, Documents))
 
 
 # Re-order the factor by Overall.N
 title <- sm.scopus.merged %>% arrange(desc(Overall.N)) %>% 
     distinct(Abbrev) %>% filter(!is.na(Abbrev)) %>% distinct()
 
 title.order = title$Abbrev
 
 sm.scopus.merged$Abbrev <- factor(sm.scopus.merged$Abbrev, levels = (title.order))
 sm.scopus.merged <- group_by(sm.scopus.merged, Journal) %>%
     mutate(Overall.Scopus = sum(Documents, na.rm=TRUE)) %>%
     ungroup()
# 
 # Create labels for the facets
 Overall.N <- distinct(sm.scopus.merged, Abbrev) 
 lab1 <- gsub(" ", "", paste("N=", pretty(Overall.N$Overall.N), sep=""))
 lab2 <- gsub(" ", "", paste("N=", pretty(Overall.N$Overall.Scopus), sep=""))
 lab <- paste(lab1, lab2, sep="\n")
 xpos = rep(1999, 79)
 ypos = rep(200, 79)
 ldata <- data.frame(xpos, ypos, lab, Overall.N$Abbrev) %>% 
     rename(Abbrev = Overall.N.Abbrev) 
 
 ldata <- na.omit(ldata)
 
 
 titles.reduced <- unique(sm.scopus.merged$Journal)
 titles.reduced.1 <- titles.reduced[1:40]
 titles.reduced.2 <- titles.reduced[41:length(titles.reduced)] 
 cp <- c("#fdb864", "#e66101", "#b2abd2", "#5e3c99" )
 
 library(grid)
 library(gridExtra)
# Plotting function    
# 
 plotSmallMultiples.1 <-  ggplot(sm.scopus.merged[sm.scopus.merged$Journal %in% titles.reduced.1, ],  aes(Year, N)) +
     geom_line(colour="#e66101") +
     geom_line(data = sm.scopus.merged[sm.scopus.merged$Journal %in% titles.reduced.1, ], aes(Year, Documents), colour = "#533c99", alpha = .80) + 
     facet_wrap(~ Abbrev) + 
     theme_bw() +
     theme(strip.text.x = element_text(size = 8)) + 
     theme(legend.position = "bottom", 
     panel.grid.minor = element_blank(), 
     axis.text.x = element_text(angle=45, hjust=1, size =8)) + 
     geom_text(data = ldata[1:40, ], aes(x =xpos, y = ypos, label = lab), size =2.5) +
     ylim(c(0,225)) +
     scale_x_continuous(breaks=seq(1989, 2015, 8)) +
     annotate("segment", x = 1989, xend = 1992, y = 215, yend = 215, colour = "#e66101") + 
     annotate("segment", x = 1989, xend = 1992, y = 190, yend = 190, colour = "#533c99") +
     ggtitle("Figure 1. Number of Article Records by Journal (1989 - 2013)")

plotSmallMultiples.2 <- ggplot(sm.scopus.merged[sm.scopus.merged$Journal %in% titles.reduced.2, ],  
     aes(Year, N)) +
     geom_line(colour="#e66101") +
     geom_line(data = sm.scopus.merged[sm.scopus.merged$Journal %in% titles.reduced.2, ], 
     aes(Year, Documents), colour = "#533c99", alpha = .80) + 
     facet_wrap(~ Abbrev) + 
     theme_bw() +
     theme(strip.text.x = element_text(size = 8)) +  
     theme(legend.position = "bottom", 
     panel.grid.minor = element_blank(), 
     axis.text.x = element_text(angle=45, hjust=1, size =8)) + 
     geom_text(data = ldata[41:79, ], aes(x =xpos, y = ypos, label = lab), size =2.5) +
     ylim(c(0,225)) +
     scale_x_continuous(breaks=seq(1989, 2015, 8)) +
     annotate("segment", x = 1989, xend = 1992, y = 215, yend = 215, colour = "#e66101") + 
     annotate("segment", x = 1989, xend = 1992, y = 190, yend = 190, colour = "#533c99") +
     ggtitle("Figure 1 (cont.). Number of Article Records by Journal (1989 - 2013)")
```

```{r plot03_AuthorPages, eval=FALSE, cache=FALSE}

#----------------------------
#Authors
#----------------------------


year.df <- full.df %>%
    filter(attributes == "pubYear") %>%
    select(id = articleID, pubYear = record)

authors.df <- full.df %>%
    filter(attributes == "author") %>%
    select(id = articleID, author = record)

n_authors <- authors.df %>%
    group_by(id) %>%
    summarise(n=n())



n_authors <- n_authors%>% 
    left_join(year.df) %>%
    group_by(pubYear) %>%
    mutate(n = as.numeric(n)) %>%
    summarise(median.n = median(n),
        average.n = mean(n),
        min.n = min(n),
        max.n = max(n),
        std.dev  = sd(n) )

n_authors2 <- n_authors%>% 
   select(median.n, average.n, std.dev) %>%
   rename(Median = median.n, Average = average.n, Standard_Deviation =std.dev)


n_authors2$year <- c(1989:2013)


cp <- c("#fdb864", "#e66101", "#b2abd2", "#5e3c99" )

n_authors2.melted <- reshape2::melt(n_authors2, id.vars = c("year", "Standard_Deviation"))
n_authors3.melted <- filter(n_authors2.melted, variable == "Average")

plot.author.count <- ggplot(n_authors2.melted, aes(x = year, y = value, group=variable, colour = variable)) + 
    theme_bw() + 
    geom_line() +
    geom_point(data = n_authors3.melted, aes(size = Standard_Deviation), colour = "#e66101", alpha=.60) + 
    #theme(axis.text.x = element_text(angle = 45, hjust = 1), 
    #title = element_text(size = 10)) +  
    scale_x_continuous(breaks=c(seq(1989, 2013, 4))) +
    scale_y_continuous(limits = c(.75,2.5)) +
    ylab("Number of Authors") +
    xlab("") +
    labs(size = "SD = ") +
    labs(colour = NULL) + 
    scale_colour_manual(values = c("#fdb864", "#e66101")) +
    theme(axis.title.x = element_text(vjust=-0.5), 
          axis.title.y = element_text(vjust=.75), 
          legend.position = "bottom") + 
       theme(title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size=8), 
    title = element_text(size = 10), plot.title=element_text(size=10)) +
    theme(legend.text = element_text(size = 8), legend.title = element_text(face="plain"))


n_authors_grouped <- n_authors %>%
    mutate(n = ifelse(n >= 4, 4, n)) %>%
    group_by(pubYear) %>%
    mutate(n.year = n()) %>%
    group_by(pubYear, n) %>%
    summarize(N =  n()) %>%
    group_by(pubYear) %>%
    mutate(N.year.overall = sum(N)) %>%
    mutate(N.percent = (N/N.year.overall)*100)



ggplot(n_authors_grouped, aes(pubYear, N.percent, group = n, colour = as.factor(n))) + geom_line(size = 1.5) + 
    scale_colour_manual(values = cp) +
    labs(colour = "Number of Authors") + 
    ylim(c(0,100)) + 
    theme(axis.title.x = element_text(vjust=-0.5), axis.title.y = element_text(vjust=.75), 
          legend.position = "bottom") +
    theme(axis.text.x = element_text(size=8), 
    title = element_text(size = 10), plot.title=element_text(size=10))

```

```{r eval=FALSE}
#----------------------------
#Pages
#----------------------------



cp <- c("#fdb864", "#e66101", "#b2abd2", "#5e3c99" )
pages.tmp <- full.df %>% filter(attributes == "pages")
years.tmp <- full.df %>% filter(attributes == "pubYear")
pages.df <- left_join(pages.tmp, years.tmp, by = "articleID") %>% 
    select(record.y, record.x) %>%
    rename(years = record.y, pages = record.x) %>%
    mutate(pages = as.numeric(pages), years = as.numeric(years)) %>%
    group_by(years) %>%
    summarise(
        Median = median(pages, na.rm=TRUE), 
        Average = mean(pages, na.rm=TRUE),
        Std.Pages = sd(pages, na.rm=TRUE))



pages.df$years <- c(1989:2013)

pages.df.melted <- reshape2::melt(pages.df, id.vars = c("years", "Std.Pages"))

pages.df2.melted <- filter(pages.df.melted, variable == "Average")

page.plot <- ggplot(pages.df.melted, aes(x = years, y = value, group=variable, colour = variable)) + 
    geom_line() +
    geom_point(data = pages.df2.melted, aes(size = Std.Pages), colour = "#5e3c99", alpha = .60) + 
    theme_bw() + 
    theme(title = element_text(size = 10)) +  
    scale_x_continuous(breaks=c(seq(1989, 2013, 4))) +
    ylab("Number of Pages") +
    xlab("") +
    labs(size = "SD = ") +
     labs(colour = NULL) +   
    scale_colour_manual(values = c("#b2abd2", "#5e3c99"))  +
    theme(axis.title.x = element_text(vjust=-0.5), axis.title.y = element_text(vjust=.75), 
          legend.position = "bottom") +
    theme(axis.text.x = element_text(size=8), 
    title = element_text(size = 10), plot.title=element_text(size=10)) +
    theme(legend.text = element_text(size = 8), legend.title = element_text(face="plain"))

```



```{r CAGR comparison, eval=FALSE}

CAGR <- function(start, finish, periods){
  # Function to compute the CAGR given simple returns
  #
  # args:
  #  start = starting value
  #  finish = ending cumulative value
  #  periods = number of time periods over which value was accumulated
  #
  # Returns the Compound Annual Growth Rate
    cagr <- round(((finish/start)^(1 /periods) - 1)*100, digits=1)    
  return(cagr)
}

setwd("/Users/beperron/Git/SocialWorkResearch/Data")
sangam <- read.csv("sangam.csv")

sangam.cumsum <-sangam %>%
  group_by(field) %>%
  mutate(CumSum=cumsum(count))

cagr <- sangam.cumsum %>%
  filter(year==1989 | year==1998)%>%
  group_by(field)%>%
  mutate(cagr=CAGR(start=min(CumSum), finish=max(CumSum), periods=9)) %>%
  select(field, cagr)

cagr<-unique(cagr)

############## Generate comparable social work CAGR, 1989-1998 #################

sw.cagr <- articles.df %>%
  filter(Year<1999 & Year>1988)%>%
  mutate(CumSum=cumsum(N)) %>%
  mutate(field = "socialWork")

sw.cagr <- sw.cagr %>%
  mutate(cagr=CAGR(start=min(CumSum), finish=max(CumSum), periods=9))%>%
  select(field, cagr)

sw.cagr<-unique(sw.cagr)

cagr<-rbind(cagr, sw.cagr)

cagr$field<-as.character(cagr$field)
cagr$field<-reorder(cagr$field, cagr$cagr)

#############PLOT##################

CAGR <- ggplot(cagr, aes(x=field, y=cagr, fill=field, group =1)) + theme_bw() + 
    geom_bar(width=0.8, stat='identity') + theme(axis.text.x = element_text(size=8),
        title = element_text(size = 10), plot.title=element_text(size=10)) + 
    ylab("Compound annual growth rate (%)") + 
    xlab("") + 
    ggtitle("Figure 4. Compound annual growth rates for \nnumber of published articles (1989 - 1998)") + 
    theme(plot.title = element_text(size = rel(1.5))) + scale_y_continuous(breaks =
        c(seq(0, 40,  15)), limits=c(0, 40)) + theme(axis.title.x =
        element_text(vjust=-0.5), axis.title.y = element_text(vjust=.75)) + 
    scale_fill_manual(values=c("#b2abd2", "#b2abd2", "#fdb863", "#b2abd2",
        "#b2abd2", "#b2abd2", "#b2abd2"))+ theme(legend.position="none") + 
    scale_x_discrete(labels=c("Psychology","Economics","Social \nWork","Sociology","Political \nScience", "History", "Anthropology")) + 
    geom_hline(yintercept=seq(0, 40, 15), col="white", lwd=0.6) + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  
        panel.border = element_blank(), axis.line = element_line(), 
        axis.text.y = element_text(size = 15),
        axis.text.x = element_text(size = 15),
        axis.title.y = element_text(size = 15), 
        title = element_text(size = 13)
        ) + 
    geom_text(aes(label =cagr ), vjust = -.5) 

    
```




```{r appendix_A_intersection, eval=FALSE}
unique.swHistory <- filter(full.df, attributes == "journal") %>%
    distinct(record)

hodge.swHistory.intersect <- intersect(hodge, unique.swHistory$record)

hodge.swHistory.diff <- setdiff(hodge, unique.swHistory$record)

```





\newpage

```{r finalArticleListecho=FALSE, comment=NA, eval=FALSE}
#print.data.frame(final.list, row.names=FALSE)
```

\newpage



```{r, eval=FALSE}
grid.arrange(plot.journal.count, plot.article.count, ncol=2)

```
\newpage
```{r fig.height=10, fig.width=7.5, eval=FALSE}
plotSmallMultiples.1

```

\newpage
```{r fig.height=10, fig.width=7.5, eval=FALSE}
plotSmallMultiples.2

```




\newpage


```{r eval=FALSE}

grid.arrange(plot.author.count, page.plot, ncol = 2)
```

\newpage

```{r eval=FALSE}
evidence.plot
```
\newpage

```{r eval=FALSE}
stacked.plot
```


\newpage
```{r eval=FALSE}
grid.arrange(journal.evidence.plot, propPlot, 
        ncol=2, nrow=1, widths=c(2, 1), heights=c(1.4, 4))
```


\newpage

# Appendix A

Articles on Hodge and Lacasse (2011) but not in the current study.  

```{r appendix_Print, eval=FALSE}
print(sort(hodge.swHistory.diff))
print(fewArticles)
```
