---
title: "Object Maker"
output: pdf_document
---


# Ebsco Full

```{r warning=FALSE, message=FALSE, eval=TRUE}
# Clear workspace
rm(list=ls())

# Read BWR functions for Mac OS
source("/Users/beperron/Git/BibWrangleR/functions/ebscoBWR.R")

# Set the path where original raw data are stored
setwd("/Users/beperron/Git/SocialWorkResearch/Data")

# Set the working directory to store files created by BWR functions
path <- "/Users/beperron/Git/SocialWorkResearch/Data/ebscoFULL"

# Wrangle the data with the BWR function suite

ebscoBWR.f(csv=FALSE, path=path, psycInfoOnly=FALSE)
save(ebscoBWR.df, file = "ebscoFULL.R")
```

# PsychInfo Only

```{r warning=FALSE, message=FALSE, eval=TRUE}
# Clear workspace
rm(list=ls())

# Read BWR functions for Mac OS
source("/Users/beperron/Git/BibWrangleR/functions/ebscoBWR.R")

# Set the path where original raw data are stored
setwd("/Users/beperron/Git/SocialWorkResearch/Data")

# Set the working directory to store files created by BWR functions
path <- "/Users/beperron/Git/SocialWorkResearch/Data/ebscoPsycInfo"

# Wrangle the data with the BWR function suite

ebscoBWR.f(csv=FALSE, path=path, psycInfoOnly=TRUE)
save(ebscoBWR.df, file = "PsychInfo.R")
```

# ProQuest

```{r warning=FALSE, message=FALSE, eval=TRUE}
# Clear workspace
rm(list=ls())

# Read BWR functions for Mac OS
source("/Users/beperron/Git/BibWrangleR/functions/proquestBWR.R")

# Set the path where original raw data are stored
setwd("/Users/beperron/Git/SocialWorkResearch/Data")

# Set the working directory to store files created by BWR functions
path <- "/Users/beperron/Git/SocialWorkResearch/Data/ProQuest"

# Wrangle the data with the BWR function suite

proQuestBWR.f(csv=FALSE, path=path)
save(proQuestBWR.df, file = "ProQuest.R")
```









